# default language
language: generic

env:
  global:
    - CLI_VERSION=latest

matrix:
  include:
    # compile example sketches for the following boards
    - env:
        - BOARD='arduino:avr:mega:cpu=atmega2560'
      install:
        - arduino-cli core install arduino:avr

    - env:
        - BOARD='arduino:samd:mkrzero'
      install:
        - arduino-cli core install arduino:samd

    - env:
        - BOARD='arduino:megaavr:uno2018:mode=on'
      install:
        - arduino-cli core install arduino:megaavr

    - env:
        - BOARD='arduino:sam:arduino_due_x'
      install:
        - arduino-cli core install arduino:sam

    # check all files for commonly misspelled words
    - env:
        - NAME='Spell Check'
      language: python
      python: 3.6
      before_install:
        # https://github.com/codespell-project/codespell
        - pip install codespell
      script:
        # codespell will ignore any words in extras/codespell-ignore-words-list.txt, which may be used to fix false positives
        - codespell --skip="${TRAVIS_BUILD_DIR}/.git" --ignore-words="${TRAVIS_BUILD_DIR}/extras/codespell-ignore-words-list.txt" "${TRAVIS_BUILD_DIR}"

# default phases shared by the compilation tests
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mkdir -p "$HOME/bin"
  - mv arduino-cli "$HOME/bin"
  - export PATH="$PATH:$HOME/bin"
  - arduino-cli core update-index
  - buildExampleSketch() { arduino-cli compile --verbose --warnings all --fqbn $BOARD "$PWD/examples/$1"; }
  - mkdir -p "$HOME/Arduino/libraries"
  - ln -s "$PWD" "$HOME/Arduino/libraries/."

script:
  - buildExampleSketch CardInfo
  - buildExampleSketch Datalogger
  - buildExampleSketch DumpFile
  - buildExampleSketch Files
  - buildExampleSketch listfiles
  - buildExampleSketch ReadWrite

notifications:
  webhooks:
    # use TravisBuddy to comment on any pull request that results in a failed CI build
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
